In [116]:
with open("in.txt", 'r') as f:
    board = f.read()
print(board)

with open("in.txt", 'r') as f:
    data = f.read().splitlines()
print(data)
print(data[len(data)-50:])
print(len(data))


Button A: X+29, Y+71
Button B: X+52, Y+31
Prize: X=5388, Y=4716

Button A: X+47, Y+16
Button B: X+14, Y+21
Prize: X=4795, Y=2996

Button A: X+21, Y+11
Button B: X+12, Y+60
Prize: X=741, Y=2859

Button A: X+61, Y+34
Button B: X+17, Y+50
Prize: X=2223, Y=12510

Button A: X+49, Y+84
Button B: X+71, Y+22
Prize: X=6954, Y=8830

Button A: X+63, Y+94
Button B: X+79, Y+28
Prize: X=3313, Y=2966

Button A: X+63, Y+34
Button B: X+16, Y+47
Prize: X=2601, Y=19683

Button A: X+58, Y+16
Button B: X+34, Y+69
Prize: X=1538, Y=782

Button A: X+32, Y+13
Button B: X+33, Y+65
Prize: X=14263, Y=17657

Button A: X+61, Y+12
Button B: X+28, Y+67
Prize: X=11219, Y=19511

Button A: X+31, Y+67
Button B: X+63, Y+23
Prize: X=12991, Y=911

Button A: X+13, Y+29
Button B: X+55, Y+38
Prize: X=2352, Y=12511

Button A: X+55, Y+31
Button B: X+26, Y+45
Prize: X=8031, Y=11372

Button A: X+27, Y+17
Button B: X+21, Y+46
Prize: X=13241, Y=17761

Button A: X+17, Y+36
Button B: X+57, Y+29
Prize: X=9818, Y=2628

Button A: X+26, Y

In [117]:
import re

reg = r'Button ([A|B]): X[+](\d*), Y[+](\d*)'
reg_prize = r'Prize: X[=](\d*), Y[=](\d*)'

res = []
for i in range (len(data)):
    if re.match(reg, data[i]):
        res.append(re.match(reg, data[i]).groups())
    if re.match(reg_prize, data[i]):
        res.append(re.match(reg_prize, data[i]).groups())
print(res)


[('A', '29', '71'), ('B', '52', '31'), ('5388', '4716'), ('A', '47', '16'), ('B', '14', '21'), ('4795', '2996'), ('A', '21', '11'), ('B', '12', '60'), ('741', '2859'), ('A', '61', '34'), ('B', '17', '50'), ('2223', '12510'), ('A', '49', '84'), ('B', '71', '22'), ('6954', '8830'), ('A', '63', '94'), ('B', '79', '28'), ('3313', '2966'), ('A', '63', '34'), ('B', '16', '47'), ('2601', '19683'), ('A', '58', '16'), ('B', '34', '69'), ('1538', '782'), ('A', '32', '13'), ('B', '33', '65'), ('14263', '17657'), ('A', '61', '12'), ('B', '28', '67'), ('11219', '19511'), ('A', '31', '67'), ('B', '63', '23'), ('12991', '911'), ('A', '13', '29'), ('B', '55', '38'), ('2352', '12511'), ('A', '55', '31'), ('B', '26', '45'), ('8031', '11372'), ('A', '27', '17'), ('B', '21', '46'), ('13241', '17761'), ('A', '17', '36'), ('B', '57', '29'), ('9818', '2628'), ('A', '26', '43'), ('B', '53', '23'), ('9328', '13971'), ('A', '22', '80'), ('B', '80', '64'), ('5684', '5920'), ('A', '45', '98'), ('B', '94', '37'), 

In [118]:
items = []
i = 0
while i < len(res):
    x = []
    for j in range(i,i+3):
        x.append(res[j])
    items.append(x)
    i+=3
items


[[('A', '29', '71'), ('B', '52', '31'), ('5388', '4716')],
 [('A', '47', '16'), ('B', '14', '21'), ('4795', '2996')],
 [('A', '21', '11'), ('B', '12', '60'), ('741', '2859')],
 [('A', '61', '34'), ('B', '17', '50'), ('2223', '12510')],
 [('A', '49', '84'), ('B', '71', '22'), ('6954', '8830')],
 [('A', '63', '94'), ('B', '79', '28'), ('3313', '2966')],
 [('A', '63', '34'), ('B', '16', '47'), ('2601', '19683')],
 [('A', '58', '16'), ('B', '34', '69'), ('1538', '782')],
 [('A', '32', '13'), ('B', '33', '65'), ('14263', '17657')],
 [('A', '61', '12'), ('B', '28', '67'), ('11219', '19511')],
 [('A', '31', '67'), ('B', '63', '23'), ('12991', '911')],
 [('A', '13', '29'), ('B', '55', '38'), ('2352', '12511')],
 [('A', '55', '31'), ('B', '26', '45'), ('8031', '11372')],
 [('A', '27', '17'), ('B', '21', '46'), ('13241', '17761')],
 [('A', '17', '36'), ('B', '57', '29'), ('9818', '2628')],
 [('A', '26', '43'), ('B', '53', '23'), ('9328', '13971')],
 [('A', '22', '80'), ('B', '80', '64'), ('5684'

In [119]:
import numpy as np

A = np.array([[int(res[0][1]), int(res[1][1])],[int(res[0][2]), int(res[1][2])]])
print(A)

b = np.array([int(res[2][0]), int(res[2][1])])
print(b)

x = np.linalg.solve(A, b)
x

[[29 52]
 [71 31]]
[5388 4716]


array([28., 88.])

In [120]:
import math as Math

results = []
the_rest= []
for item in items:
    A = np.array([[int(item[0][1]), int(item[1][1])],[int(item[0][2]), int(item[1][2])]])
    b = np.array([int(item[2][0]) + 10000000000000, int(item[2][1]) + 10000000000000])
    x = np.linalg.solve(A, b)
    # print(A)
    # print(b)
    # print(x)
    # print(np.round(x[0]))
    # check if x is integer
    res1 = np.round(x[0]) * A[0][0] + np.round(x[1]) * A[0][1]
    res2 = np.round(x[0]) * A[1][0] + np.round(x[1]) * A[1][1]
    # print(b)
    # print(res1, res2)
    # print(sum(b == [res1, res2]))
    if sum(b == [res1, res2]) == 2:
        print("SOLVABLE")
        print(item)
        results.append(x)
    else:
        # print("WRONG")
        # print(x)
        # print(b)
        # print(res1, res2)
        the_rest.append(x)

results
# the_rest

SOLVABLE
[('A', '61', '34'), ('B', '17', '50'), ('2223', '12510')]
SOLVABLE
[('A', '63', '34'), ('B', '16', '47'), ('2601', '19683')]
SOLVABLE
[('A', '32', '13'), ('B', '33', '65'), ('14263', '17657')]
SOLVABLE
[('A', '61', '12'), ('B', '28', '67'), ('11219', '19511')]
SOLVABLE
[('A', '31', '67'), ('B', '63', '23'), ('12991', '911')]
SOLVABLE
[('A', '13', '29'), ('B', '55', '38'), ('2352', '12511')]
SOLVABLE
[('A', '55', '31'), ('B', '26', '45'), ('8031', '11372')]
SOLVABLE
[('A', '27', '17'), ('B', '21', '46'), ('13241', '17761')]
SOLVABLE
[('A', '17', '36'), ('B', '57', '29'), ('9818', '2628')]
SOLVABLE
[('A', '26', '43'), ('B', '53', '23'), ('9328', '13971')]
SOLVABLE
[('A', '13', '67'), ('B', '67', '15'), ('4487', '19239')]
SOLVABLE
[('A', '49', '13'), ('B', '22', '44'), ('8574', '8268')]
SOLVABLE
[('A', '46', '16'), ('B', '17', '69'), ('15584', '17398')]
SOLVABLE
[('A', '12', '31'), ('B', '62', '21'), ('10044', '15067')]
SOLVABLE
[('A', '13', '34'), ('B', '65', '15'), ('14563', '2

[array([1.33495146e+11, 1.09223301e+11]),
 array([1.28258171e+11, 1.19983451e+11]),
 array([1.93821926e+11, 1.15081769e+11]),
 array([1.03972274e+11, 1.30631832e+11]),
 array([1.14025085e+11, 1.02622577e+11]),
 array([1.54405087e+11, 1.45322434e+11]),
 array([1.13840623e+11, 1.43798682e+11]),
 array([2.82485876e+11, 1.12994351e+11]),
 array([1.79602309e+11, 1.21872996e+11]),
 array([1.7846520e+11, 1.0113028e+11]),
 array([1.21099208e+11, 1.25756870e+11]),
 array([1.17647059e+11, 1.92513369e+11]),
 array([1.79186768e+11, 1.03376982e+11]),
 array([2.45508982e+11, 1.13772455e+11]),
 array([2.48138958e+11, 1.04218363e+11]),
 array([1.02796053e+11, 1.15131579e+11]),
 array([1.02040816e+11, 1.89504373e+11]),
 array([1.16279070e+11, 1.09011628e+11]),
 array([1.08024692e+11, 1.00308642e+11]),
 array([1.22914838e+11, 1.25841381e+11]),
 array([1.05900152e+11, 1.21028744e+11]),
 array([2.48618785e+11, 1.01289135e+11]),
 array([1.28458498e+11, 1.08695652e+11]),
 array([1.02195307e+11, 1.15442846e+

In [121]:
sumA = sum([x[0] for x in results])
sumB = sum([x[1] for x in results])
print(sumA, sumB)
print((sumA * 3) + sumB)


20647010695682.0 20629666513424.0
82570698600470.0
