In [4]:
# import required libraries
import cv2

# read input image
img = cv2.imread('eyes.png')

# convert to grayscale of each frames
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# read the haarcascade to detect the faces in an image
face_cascade = cv2.CascadeClassifier('haarcascades\haarcascade_frontalface_default.xml')

# read the haarcascade to detect the eyes in an image
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

print('Face cascade:', face_cascade)
print('eye cascade:', eye_cascade)
# detects faces in the input image

# faces = face_cascade.detectMultiScale(gray, 1.3, 5)
#faces = face_cascade.detectMultiScale(gray)

eyes = eye_cascade.detectMultiScale(gray)
print('Eyes:', eyes, " >> ", len(eyes))
for (ex,ey,ew,eh) in eyes:
    cv2.rectangle(img,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

# cv2.imshow('img',img)

# display the image with detected eyes
cv2.imshow('Eyes Detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<>:11: SyntaxWarning: invalid escape sequence '\h'
<>:11: SyntaxWarning: invalid escape sequence '\h'
/var/folders/fc/hf24rcz55cv3vj2_ny6pb4y00000gn/T/ipykernel_58169/2013276042.py:11: SyntaxWarning: invalid escape sequence '\h'
  face_cascade = cv2.CascadeClassifier('haarcascades\haarcascade_frontalface_default.xml')
[ERROR:0@46.626] global persistence.cpp:531 open Can't open file: 'haarcascades\haarcascade_frontalface_default.xml' in read mode


Face cascade: < cv2.CascadeClassifier 0x113313d30>
eye cascade: < cv2.CascadeClassifier 0x1325e9330>
Eyes: [[1091   76  154  154]
 [ 382  401  256  256]
 [ 105  485   47   47]
 [1125  646   22   22]
 [ 771  415  128  128]
 [  27  398  275  275]
 [1022  740  297  297]
 [ 826  925   48   48]
 [ 251  921   52   52]
 [ 825  830   80   80]
 [ 428  774  121  121]
 [1158 1110   46   46]
 [1128 1100  101  101]
 [ 457 1120  184  184]
 [1078 1301   23   23]]  >>  15


In [ ]:
import cv2
import numpy as np

In [9]:
# Load Yolo
net = cv2.dnn.readNetFromDarknet("yolov3.weights", "yolov3.cfg")
classes = []
with open("coco.names", "r") as f:
    classes = [line.strip() for line in f.readlines()]
print(classes)
layer_names = net.getLayerNames()
output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
colors = np.random.uniform(0, 255, size=(len(classes), 3))

error: OpenCV(4.10.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/darknet/darknet_importer.cpp:210: error: (-212:Parsing error) Failed to open NetParameter file: yolov3.weights in function 'readNetFromDarknet'


: 